name: Bug report
description: Create a bug report to help us improve
labels: ['🐛 bug']
assignees: me
body:
  - type: markdown
    attributes:
      value: |
        What's the problem G ?
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: Describe it.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: How to reproduce
      description: Steps to reproduce the behavior
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.

  - type: textarea
    id: solution
    attributes:
      label: Possible solution ?
      description: Optionally describe how you'd solve this.
    validations:
      required: false
