name: Feature request
labels: ['⭐ feature']
description: Features & such
assignees: me
body:
  - type: textarea
    attributes:
      label: New feature description
      description: Describe the functional changes that would have to be made.
    validations:
      required: true

  - type: textarea
    attributes:
      label: New feature implementation
      description: Optionally describe the technical changes to be made.
    validations:
      required: false
