import CookieBanner from '@/components/CookieBanner';
import CloudflareWebAnalyticsProvider from '@/components/providers/CloudflareAnalytics';
import { env } from '@/lib/env';
import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';

import './styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body>{children}</body>
      <CookieBanner />
      <CloudflareWebAnalyticsProvider
        token={env.NEXT_PUBLIC_CLOUDFLARE_ANALYTICS_TOKEN}
      />
    </html>
  );
}
