name: Vercel Build

description: Build to deploy to vercel

inputs:
  NODE_ENV:
    description: ''
    required: true
  VERCEL_TOKEN:
    description: 'Vercel token for authentication'
    required: true
  VERCEL_ORG_ID:
    description: 'Vercel organization ID'
    required: true
  VERCEL_PROJECT_ID:
    description: 'Vercel project ID'
    required: true
  NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID:
    description: ''
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/pnpm-install
    - uses: ./.github/actions/setup-env
      with:
        NODE_ENV: ${{ inputs.NODE_ENV }}
        NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID: ${{ inputs.NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID }}

    - name: Build for Vercel
      shell: bash
      env:
        VERCEL_TOKEN: ${{ inputs.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ inputs.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ inputs.VERCEL_PROJECT_ID }}

      run: |
        pnpm build:vercel-${{ inputs.NODE_ENV }} --token=$VERCEL_TOKEN
