name: 'Setup Environment Variables'
description: 'Sets up env from GitHub Secrets'
inputs:
  NODE_ENV:
    description: "either 'development', 'preview', or 'production' & defo not 'prod' or 'dev'"
    required: true
  NEXT_PUBLIC_CLOUDFLARE_ANALYTICS_TOKEN:
    description: 'Cloudflare analytics token'
    required: true
  NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION:
    description: 'Google site verification'
    required: true

runs:
  using: composite
  steps:
    - name: Set up .env
      shell: bash
      run: |
        declare -A env_vars=(
          ["NODE_ENV"]="${{ inputs.NODE_ENV }}"
          ["NEXT_PUBLIC_CLOUDFLARE_ANALYTICS_TOKEN"]="${{ inputs.NEXT_PUBLIC_CLOUDFLARE_ANALYTICS_TOKEN }}"
          ["NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION"]="${{ inputs.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION }}"
        )

        for key in "${!env_vars[@]}"; do
          echo "${key}='${env_vars[$key]}'" >> .env
        done
