name: Triage Bug Reports

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  issues: write

jobs:
  triage:
    name: Bug Report Triage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Nissuer for Issue Triage
        uses: balazsorban44/nissuer@1.10.0
        with:
          label-area-prefix: ""
          label-area-match: "name"
          label-area-section: "Bug description(.*)How to reproduce"

          label-comments: |
            {
              "🐛 bug": ".github/comments/bug-report.md",
              "missing reproduction": ".github/comments/missing-reproduction.md",
              "incomplete description": ".github/comments/incomplete-description.md"
            }

          # Require reproduction link validation
          reproduction-comment: ".github/comments/invalid-reproduction.md"
          reproduction-hosts: "github.com,bitbucket.org,gitlab.com,codesandbox.io,stackblitz.com"
          reproduction-blocklist: 'github.com/\\w*/?$,github.com$'
          reproduction-link-section: "### How to reproduce(.*)### Expected behavior"
          reproduction-invalid-label: "missing reproduction"
          reproduction-issue-labels: "🐛 bug,"
          comment-unhelpful-weight: 0.5
