# this is here for the samentic release with conventional commits, needa make sure no commits are off
name: PR

on:
  workflow_dispatch:
  workflow_call:

jobs:
  validate-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: "ashgw/ashgw.me"

      - name: Assign PR to opener
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          OPENER: ${{ github.event.pull_request.user.login }}
        run: |
          curl -H "Authorization: token ${GITHUB_TOKEN}" \
              -X POST \
              -d "{\"assignees\": [\"${OPENER}\"]}" \
              https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/assignees

      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR if title lint fails
        if: always() && steps.lint_pr_title.outputs.error_message != null
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          message: |
            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) for valid changelog entries and it looks like your proposed title needs to be adjusted.
            Details:
            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```
